# Generated by Django 5.1.1 on 2024-09-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descrpción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('available', models.BooleanField(default=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Imagen del producto')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Fecha de actuaización')),
            ],
        ),
    ]
